# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20171120_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sign',
        ),
    ]
